fix applyScopes method to support Collection
yajra/laravel-datatables-buttons pull request #168
Opened 2023-02-05 08:21 UTC by g3c0d3r5

This pull request fix the issue that when we create a DataTable service from php artisan datatables:make command, the service cannot support CollectionDatatable because applyScopes method in Yajra\DataTables\Services\DataTable class only support EloquentBuilder|QueryBuilder|EloquentRelation.

2023-02-06 03:22 UTC, yajra requested changes
Changes look good but the static analysis is failing. Can you please make it pass? Thanks!

2023-02-07 01:19 UTC, yajra commented
@g3c0d3r5 the latest patch still fails. Thanks!

2023-02-07 13:57 UTC, g3c0d3r5 commented
Oops, sorry for the missing backslash...

2023-02-20 06:08 UTC, yajra approved these changes

2023-02-20 06:08 UTC, merged

2023-02-20 06:11 UTC, yajra commented
Released on v9.1.4 🚀 Thanks!

2023-02-20 06:56 UTC, dinhquochan commented
Hello @yajra,

This is a breaking change. Many clients will be 500 errors caused by this PR. Why you accepted a change to the signature in 1 minor version?  🥹

2023-02-20 06:56 UTC, dinhquochan commented
It should be merged in version 10.x

2023-02-20 06:58 UTC, dinhquochan commented
😱 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/9979458/220034845-f3c1193f-16d7-4640-bd98-ed127a40c1bd.png">

2023-02-20 07:01 UTC, yajra commented
Oh no, the tests are passing. I will check again and revert if needed. It was already merged in 10.x too.

2023-02-20 07:13 UTC, dinhquochan commented
I've updated it by myself 🥲 @yajra do not revert 🥶

2023-02-20 07:14 UTC, yajra commented
Can you provide some snippets to reproduce your issue? Might also cause issue on others.

2023-02-20 07:17 UTC, yajra commented
Oh, I think you are extending to your own service class. An isolated case I guess.

2023-02-20 07:17 UTC, dinhquochan commented
@yajra I just extended `DataTable::class` and overridden `applyScope()` method. Because the return type change, the child class should be an error.

2023-02-20 07:18 UTC, yajra commented
That makes sense, sorry for the trouble. But it's a needed fix.

2023-02-20 08:23 UTC, yajra commented
@dinhquochan sorry in advance again and heads up. On **v10** I will update the stub again to allow AnonymousResourceCollection. See https://github.com/yajra/laravel-datatables-buttons/pull/170